#!/usr/bin/env python3
"""Generate synthetic EPG data in the MiddlewareSimulator pipe format.

Output lines:
  CH|id|name|provider|serviceType|lcn
  PG|channelId|programId|start|end|name|description|genre|parentalAge

Times are UTC, formatted YYYY-MM-DD HH:MM:SS - matching the C++ parser.

Example:
  python generate_epg.py --channels 10 --programs-per-channel 8 --output big_epg.txt
"""
from __future__ import annotations

import argparse
import random
from datetime import datetime, timedelta

CHANNEL_NAMES = ["BBC One", "ITV", "Channel 4", "Dave", "Film4", "Sky News",
                 "E4", "More4", "BBC Two", "Channel 5"]
PROVIDERS = ["BBC", "ITV plc", "Channel Four", "UKTV", "Sky"]
# Genres match the DVB content-nibble mapping in the C++ EitTable.
GENRES = ["Movie", "News", "Show", "Sports", "Children", "Music",
          "Arts", "Social", "Education", "Leisure"]
PROGRAM_TITLES = ["Morning News", "The Big Quiz", "Cooking Master", "Drama Hour",
                  "Live Football", "Cartoon Time", "Documentary", "Late Movie",
                  "Weather", "Talk Show"]
RATINGS = [0, 0, 0, 12, 15, 18]   # weighted toward unrated


def generate(channels: int, programs_per_channel: int, start: datetime,
             seed: int) -> list[str]:
    rng = random.Random(seed)
    lines: list[str] = []
    for channel_id in range(1, channels + 1):
        name = rng.choice(CHANNEL_NAMES)
        provider = rng.choice(PROVIDERS)
        lcn = 100 + channel_id
        lines.append(f"CH|{channel_id}|{name}|{provider}|1|{lcn}")

        slot = start
        for index in range(programs_per_channel):
            program_id = channel_id * 100 + index + 1
            end = slot + timedelta(minutes=rng.choice([30, 45, 60, 90]))
            title = rng.choice(PROGRAM_TITLES)
            genre = rng.choice(GENRES)
            rating = rng.choice(RATINGS)
            lines.append(
                f"PG|{channel_id}|{program_id}"
                f"|{slot:%Y-%m-%d %H:%M:%S}|{end:%Y-%m-%d %H:%M:%S}"
                f"|{title}|Auto-generated {genre.lower()} programme"
                f"|{genre}|{rating}"
            )
            slot = end
        lines.append("")   # blank line between channels
    return lines


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate synthetic EPG data for MiddlewareSimulator.")
    parser.add_argument("-c", "--channels", type=int, default=4,
                        help="number of channels (default: 4)")
    parser.add_argument("-p", "--programs-per-channel", type=int, default=5,
                        help="programs per channel (default: 5)")
    parser.add_argument("-o", "--output", default="simulated_data.txt",
                        help="output file path (default: simulated_data.txt)")
    parser.add_argument("-s", "--start", default="2025-04-16 06:00:00",
                        help="first program start, UTC (YYYY-MM-DD HH:MM:SS)")
    parser.add_argument("--seed", type=int, default=42,
                        help="random seed for reproducible output")
    args = parser.parse_args()

    start = datetime.strptime(args.start, "%Y-%m-%d %H:%M:%S")
    body = generate(args.channels, args.programs_per_channel, start, args.seed)

    header = [
        "# Synthetic EPG data generated by generate_epg.py",
        "# Format: CH|id|name|provider|serviceType|lcn",
        "#         PG|channelId|programId|start|end|name|description|genre|parentalAge",
        "",
    ]
    with open(args.output, "w", encoding="utf-8") as f:
        f.write("\n".join(header + body) + "\n")

    print(f"Wrote {args.channels} channels x {args.programs_per_channel} "
          f"programs to {args.output}")


if __name__ == "__main__":
    main()
